services:
  inventory:
    build: inventory/
    command: uvicorn app.main:app --reload --host 0.0.0.0
    volumes:
      - ./inventory:/app
    ports:
      - 8001:8000
  frontend:
    build: frontend/
    command: npm run dev -- -o
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:3000
